# Generated by Django 5.2.3 on 2025-06-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='workflow_ma_user_id_578e50_idx',
            old_name='workflow_m_user_id_7b0e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='workflow_ma_resourc_66b178_idx',
            old_name='workflow_m_resourc_4b2f5c_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='workflow_ma_project_83805e_idx',
            old_name='workflow_m_project_c7d8e9_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
