# Generated by Django 5.2.1 on 2025-06-05 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_increase_file_field_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chunkedupload',
            unique_together={('user', 'filename', 'chunk_number', 'project')},
        ),
        migrations.AlterField(
            model_name='chunkedupload',
            name='file',
            field=models.TextField(),
        ),
    ]
