# Generated by Django 5.2.1 on 2025-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_chunkedupload_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='file',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterModelTable(
            name='chunkedupload',
            table='storage_chunkedupload',
        ),
    ]
