# Generated by Django 5.2.3 on 2025-06-11 10:19

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_assignment_filestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=1000, upload_to=storage.models.user_directory_path),
        ),
    ]
