# Generated by Django 5.2.1 on 2025-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_role_user_last_login_ip_accesslog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='storage_quota',
            field=models.BigIntegerField(default=107374182400),
        ),
    ]
