# Generated by Claude Code - Safe migration
# This migration creates new models without modifying old ones

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20250605_0836'),
        ('users', '0003_alter_user_storage_quota'),
    ]

    operations = [
        # Create WorkflowRole model
        migrations.CreateModel(
            name='WorkflowRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'System Admin'), ('manager', 'Project Manager'), ('employee', 'Employee')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'workflow role',
                'verbose_name_plural': 'workflow roles',
                'db_table': 'workflow_roles',
            },
        ),
        
        # Add new fields to User
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='workflow_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.workflowrole'),
        ),
        
        # Create ProjectAssignment model
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='storage.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_assignments',
                'unique_together': {('user', 'project')},
            },
        ),
    ]