# Generated by Django 5.2.3 on 2025-06-11 04:39

from django.db import migrations, models
from django.db import connection

def safe_cleanup_old_models(apps, schema_editor):
    """Safely remove old models and fields if they exist"""
    if connection.vendor == 'sqlite':
        # For SQLite, we'll just ensure the is_active field is correct
        # The old models may not exist, so we skip removal operations
        pass

def reverse_safe_cleanup(apps, schema_editor):
    """Reverse operation - no-op since we can't recreate old models"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workflowrole_projectassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(safe_cleanup_old_models, reverse_safe_cleanup),
    ]
