# Generated by Django 5.2.3 on 2025-06-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_rolepermission_permission_and_more'),
    ]

    operations = [
        # State-only migration to sync with current models.py
        # This tells Django that the old Permission, Role, RolePermission models 
        # and the 'role' field on User have been removed
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='rolepermission',
                    name='permission',
                ),
                migrations.RemoveField(
                    model_name='rolepermission', 
                    name='role',
                ),
                migrations.RemoveField(
                    model_name='user',
                    name='role',
                ),
                migrations.DeleteModel(
                    name='Permission',
                ),
                migrations.DeleteModel(
                    name='RolePermission',
                ),
                migrations.DeleteModel(
                    name='Role',
                ),
            ],
            database_operations=[
                # No database operations - tables were already handled in previous migration
            ],
        ),
    ]
